name: cli_util
version: 0.0.1+2
author: Dart Team <misc@dartlang.org>
description: A library to help in building Dart command-line apps.
homepage: https://github.com/dart-lang/cli_util
environment:
  sdk: '>=1.0.0 <2.0.0'
dependencies:
  path: '>=1.0.0 <2.0.0'
  which: '>=0.1.2 <0.2.0'
dev_dependencies:
  unittest: '>=0.11.0 <0.12.0'
