name: observatory
version: 1.6.0-dev.1
transformers:
- polymer:
    entry_points:
    - web/index.html
    inline_stylesheets:
      lib/src/elements/css/shared.css: false
      packages/charted/charts/themes/quantum_theme.css: false
    $exclude: [web/third_party/*.html, web/timeline.html]
- $dart2js:
    $include: "**/*.polymer.bootstrap.dart"
    suppressWarnings: false
    commandLineOptions: [--show-package-warnings]
dependencies:
  args: any
  charted: ^0.4.0
  polymer: ^0.16.3
  unittest: < 0.12.0
  js: ^0.6.0
  js_util: ^0.2.0
  usage: any
dependency_overrides:
  analyzer: '>=0.26.1 <0.26.1+15'
  dart_style: <0.2.2
