name: observatory
version: 1.6.0-dev.1
transformers:
- dart_to_js_script_rewriter
- $dart2js:
    $include: "**/*.polymer.bootstrap.dart"
    suppressWarnings: false
    commandLineOptions: [--show-package-warnings]
dependencies:
  args: any
  charted: ^0.4.0
  unittest: < 0.12.0
  usage: any
  web_components: any
  dart_to_js_script_rewriter: any
dependency_overrides:
  analyzer: '>=0.26.1 <0.26.1+15'
  dart_style: <0.2.2
