name: string_scanner
version: 0.1.3+1
author: "Dart Team <misc@dartlang.org>"
homepage: https://github.com/dart-lang/string_scanner
description: >
  A class for parsing strings using a sequence of patterns.
dependencies:
  path: ">=1.2.0 <2.0.0"
  source_span: ">=1.0.0 <2.0.0"
dev_dependencies:
  unittest: ">=0.10.0 <0.12.0"
environment:
  sdk: ">=1.2.0 <2.0.0"
